---
abstract: "It's new $module"
author:
  - 'sue7ga <sue77ga@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Rakuten-API
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  WebService::Rakuten::API:
    file: lib/WebService/Rakuten/API.pm
    version: 0.01
  WebService::Rakuten::API::Provider:
    file: lib/WebService/Rakuten/API/Provider.pm
  WebService::Rakuten::API::Provider::Books:
    file: lib/WebService/Rakuten/API/Provider/Books.pm
  WebService::Rakuten::API::Provider::Ichiba:
    file: lib/WebService/Rakuten/API/Provider/Ichiba.pm
  WebService::Rakuten::API::Provider::Recipe:
    file: lib/WebService/Rakuten/API/Provider/Recipe.pm
  WebService::Rakuten::API::Provider::Travel:
    file: lib/WebService/Rakuten/API/Provider/Travel.pm
requires:
  perl: 5.008005
resources:
  bugtracker: https://github.com/sue7ga/WebService-Rakuten-API/issues
  homepage: https://github.com/sue7ga/WebService-Rakuten-API
  repository: git://github.com/sue7ga/WebService-Rakuten-API.git
version: 0.01
